export const POST_ACTIONS = {
  ADD_POST: 'ADD_POST',
  EDIT_POST: 'EDIT_POST',
  DELETE_POST: 'DELETE_POST',
  FETCH_POSTS: 'FETCH_POSTS',
  FILTER_POSTS: 'FILTER_POSTS'
};

export const CATEGORY_ACTIONS = {
  ADD_CATEGORY: 'ADD_CATEGORY',
  EDIT_CATEGORY: 'EDIT_CATEGORY',
  DELETE_CATEGORY: 'DELETE_CATEGORY',
  VIEW_CATEGORY: 'VIEW_CATEGORY'
};

export const COMMENT_ACTIONS = {
  EDIT_COMMENT: 'EDIT_COMMENT',
  DELETE_COMMENT: 'DELETE_COMMENT',
  FETCH_COMMENTS: 'FETCH_COMMENTS',
  FILTER_COMMENTS: 'FILTER_COMMENTS'
};

export const TAG_ACTIONS = {
  CREATE_TAG: 'CREATE_TAG',
  EDIT_TAG: 'EDIT_TAG',
  DELETE_TAG: 'DELETE_TAG',
  FETCH_TAGS: 'FETCH_TAGS',
  FILTER_TAGS: 'FILTER_TAGS'
};

export const USER_ACTIONS = {
  LOGIN: 'LOGIN',
  LOGOUT: 'LOGOUT'
};